SELECT * FROM bookings;
SELECT * FROM drivers;
SELECT * FROM messages;
SELECT * FROM payment_cards;
SELECT * FROM passengers;
SELECT * FROM reports;
SELECT * FROM trips;
SELECT * FROM wallet_accounts;
SELECT * FROM wallet_transactions;
